line-length = 120

[lint]
select = ["E", "W", "F", "I", "B", "S"]
ignore = ["E402"]

[lint.per-file-ignores]
"tests/**/*.py" = ["E402", "S101"]
"tests/*.py" = ["E402", "S101"]
"scripts/**/*.py" = ["E402", "S101"]
"scripts/*.py" = ["E402", "S101"]
