[lint]
select = ["E", "W", "F", "I", "B", "S"]
ignore = ["E501", "E402"]

[lint.per-file-ignores]
"tests/**/*.py" = ["E402"]
"tests/*.py" = ["E402"]
"scripts/**/*.py" = ["E402"]
"scripts/*.py" = ["E402"]
