"""Tests for SLPositionSizer.reconcile_with_broker (card 0e0338d4).

Covers the nuke-and-rebuild behaviour that fixes the phantom-positions
bug where the sizer reported ``positions_carried=16`` while cTrader only
had 4 actual fills.

Phantom sources verified by these tests:
  1. The ``_legacy_open_risk`` synthesis path — ``_open_risk`` setter
     creates a ``_legacy_open_risk`` key from the persisted scalar.
  2. ``register_open_position`` legacy callbacks that lack a matching
     broker position (the sizer-kept key outlasts the broker side).
  3. ``_legacy_{id}_{N}`` keys generated by repeated legacy registrations.

The fix: ``reconcile_with_broker(positions)`` clears ``_open_positions``
and rebuilds ONLY from the broker-supplied list using
``seeded_{position_id}`` keys.
"""

from __future__ import annotations  # noqa: I001

from dataclasses import dataclass
from decimal import Decimal
from typing import Optional

import pytest

from risk.sl_position_sizer import (
    SLPositionSizer,
    _compute_position_risk_usd,
)


# ── Helpers ───────────────────────────────────────────────────────────────


@dataclass
class _FakeBrokerPos:
    """Drop-in replacement for ctrader.models.Position / account_state.Position.

    Has the minimum attributes that ``reconcile_with_broker`` reads.
    """

    position_id: str
    symbol: str
    volume: float
    entry_price: float
    stop_loss: Optional[float] = None


@dataclass
class _AccountStatePos:
    """Mirrors adapters.ctrader.account_state.Position field names.

    Uses ``volume_lots`` instead of ``volume`` and ``sl`` instead of
    ``stop_loss`` so the helper code path that prefers those names is
    exercised too.
    """

    position_id: str
    symbol: str
    volume_lots: Decimal
    entry_price: Decimal
    sl: Optional[Decimal] = None
    tp: Optional[Decimal] = None
    side: str = "BUY"
    open_time: Optional[object] = None
    unrealized_pnl: Decimal = Decimal("0")


class TestReconcileWithBroker:
    def setup_method(self):
        self.sizer = SLPositionSizer(
            account_balance=100_000.0,
            risk_per_trade_pct=0.005,
            daily_risk_cap_pct=0.03,
        )

    # ── Empty broker = empty sizer ─────────────────────────────────────

    def test_empty_broker_clears_all_entries(self):
        """0 broker positions → 0 sizer entries, even if sizer has phantoms."""
        # Seed phantom entries (simulating prior-session leftovers).
        self.sizer.register("phantom-1", 50.0)
        self.sizer.register("phantom-2", 75.0)
        self.sizer.register("_legacy_open_risk", 200.0)
        self.sizer.register_open_position(40.0)
        assert len(self.sizer.open_positions) == 4

        result = self.sizer.reconcile_with_broker([])

        assert result["before_count"] == 4
        assert result["after_count"] == 0
        assert result["seeded_count"] == 0
        assert result["diverged"] is True
        assert result["before_open_risk"] == pytest.approx(365.0, abs=1e-6)
        assert result["after_open_risk"] == 0.0
        # Sizer is fully cleared.
        assert self.sizer.open_positions == {}
        assert self.sizer.open_risk == 0.0
        # No missing positions reported.
        assert result["missing_position_ids"] == []

    def test_fresh_startup_zero_broker_yields_zero_positions_carried(self):
        """Acceptance criterion: positions_carried is exactly 0 on a fresh
        startup with 0 broker positions, NOT ±1 from a legacy scalar."""
        # Simulate a freshly-restored sizer with a non-zero open_risk
        # in the state file (the exact phantom scenario the council flagged).
        self.sizer._open_risk = 150.0  # triggers the legacy_open_risk key
        assert len(self.sizer.open_positions) == 1

        result = self.sizer.reconcile_with_broker([])

        assert len(self.sizer.open_positions) == 0
        assert result["after_count"] == 0

    # ── Rebuild from broker ────────────────────────────────────────────

    def test_rebuilds_from_broker_with_seeded_keys(self):
        """Broker-reported positions are re-seeded under seeded_{id} keys
        that cannot collide with live signal_ids."""
        positions = [
            _FakeBrokerPos(
                position_id="12345",
                symbol="EURUSD",
                volume=0.10,
                entry_price=1.0850,
                stop_loss=1.0820,  # 30 pips
            ),
            _FakeBrokerPos(
                position_id="67890",
                symbol="GBPUSD",
                volume=0.20,
                entry_price=1.2700,
                stop_loss=1.2670,  # 30 pips
            ),
        ]
        result = self.sizer.reconcile_with_broker(positions)

        assert result["after_count"] == 2
        assert result["seeded_count"] == 2
        assert result["diverged"] is True  # was 0, now 2
        # Both keyed under seeded_{position_id}
        assert "seeded_12345" in self.sizer.open_positions
        assert "seeded_67890" in self.sizer.open_positions
        # Risk per position: 30 pips * 0.10 lots * $10/pip = $30
        #                   30 pips * 0.20 lots * $10/pip = $60
        # Total = $90
        assert self.sizer.open_positions["seeded_12345"] == pytest.approx(30.0)
        assert self.sizer.open_positions["seeded_67890"] == pytest.approx(60.0)
        assert self.sizer.open_risk == pytest.approx(90.0)

    def test_idempotent_when_sizer_matches_broker(self):
        """Calling reconcile twice with the same broker list yields the
        same after_count — no drift from duplicate seeding."""
        positions = [
            _FakeBrokerPos(
                position_id="111",
                symbol="EURUSD",
                volume=0.10,
                entry_price=1.0850,
                stop_loss=1.0820,
            ),
        ]
        first = self.sizer.reconcile_with_broker(positions)
        second = self.sizer.reconcile_with_broker(positions)

        assert first["after_count"] == 1
        assert second["after_count"] == 1
        assert second["before_count"] == 1
        assert second["after_count"] == second["before_count"]
        # No duplicate key — second call should NOT add a second entry.
        assert len(self.sizer.open_positions) == 1

    def test_accepts_account_state_position_dataclass(self):
        """The sizer should also accept the account_state.Position shape
        (uses ``volume_lots`` and ``sl`` rather than ``volume``/``stop_loss``)."""
        positions = [
            _AccountStatePos(
                position_id="acct-1",
                symbol="USDJPY",
                volume_lots=Decimal("0.50"),
                entry_price=Decimal("154.000"),
                sl=Decimal("153.700"),  # 30 pips (pip_size=0.01)
            ),
        ]
        result = self.sizer.reconcile_with_broker(positions)

        assert result["seeded_count"] == 1
        assert "seeded_acct-1" in self.sizer.open_positions
        # 30 pips * 0.50 lots * $6.5/pip = $97.50
        assert self.sizer.open_positions["seeded_acct-1"] == pytest.approx(97.5, abs=1e-6)

    def test_conservative_fallback_when_sl_missing(self):
        """A broker position with no SL gets ``lots * 100`` risk estimate
        (matches engine's existing fallback)."""
        positions = [
            _FakeBrokerPos(
                position_id="no-sl-1",
                symbol="EURUSD",
                volume=0.50,
                entry_price=1.0850,
                stop_loss=None,
            ),
        ]
        result = self.sizer.reconcile_with_broker(positions)
        # 0.50 lots * $100 = $50
        assert self.sizer.open_positions["seeded_no-sl-1"] == pytest.approx(50.0)
        assert result["seeded_count"] == 1

    def test_unknown_symbol_falls_back_to_fx_defaults(self):
        """Unknown symbol uses pip_size=0.0001, pip_value=$10/lot."""
        positions = [
            _FakeBrokerPos(
                position_id="exotic-1",
                symbol="ZARUSD",
                volume=0.10,
                entry_price=0.0550,
                stop_loss=0.0520,  # 30 pips under FX defaults
            ),
        ]
        _result = self.sizer.reconcile_with_broker(positions)
        # 30 pips * 0.10 lots * $10/pip = $30
        assert self.sizer.open_positions["seeded_exotic-1"] == pytest.approx(30.0)

    def test_missing_position_id_is_logged_and_skipped(self):
        """A position with no id is logged as a warning and NOT registered."""
        positions = [
            _FakeBrokerPos(
                position_id="",  # Empty id
                symbol="EURUSD",
                volume=0.10,
                entry_price=1.0850,
                stop_loss=1.0820,
            ),
            _FakeBrokerPos(
                position_id="ok-1",
                symbol="EURUSD",
                volume=0.10,
                entry_price=1.0850,
                stop_loss=1.0820,
            ),
        ]
        result = self.sizer.reconcile_with_broker(positions)

        assert result["seeded_count"] == 1
        assert result["after_count"] == 1
        assert "<missing-id>" in result["missing_position_ids"]

    def test_legacy_open_risk_phantom_gets_cleared(self):
        """Regression test for the exact phantom scenario in the card:
        _open_risk setter creates a _legacy_open_risk key on restore
        with a non-zero scalar that has no matching broker position."""
        # Simulate the restore path: legacy scalar is set, the key
        # _legacy_open_risk gets created.
        self.sizer._open_risk = 200.0
        assert "_legacy_open_risk" in self.sizer.open_positions
        assert self.sizer.open_risk == pytest.approx(200.0)

        # The broker has 0 positions (the position the legacy scalar
        # represented was closed before restart).
        result = self.sizer.reconcile_with_broker([])

        assert "_legacy_open_risk" not in self.sizer.open_positions
        assert len(self.sizer.open_positions) == 0
        assert result["before_count"] == 1
        assert result["after_count"] == 0

    def test_legacy_register_open_position_phantoms_cleared(self):
        """Legacy register_open_position calls (no matching broker position)
        get cleared by reconcile."""
        self.sizer.register_open_position(50.0)
        self.sizer.register_open_position(75.0)
        # Plus a live signal that DOES have a broker position.
        self.sizer.register("live-sig-1", 100.0)
        assert len(self.sizer.open_positions) == 3

        # Broker only reports one position (matching the live signal_id).
        positions = [
            _FakeBrokerPos(
                position_id="broker-pos-1",
                symbol="EURUSD",
                volume=0.10,
                entry_price=1.0850,
                stop_loss=1.0820,
            ),
        ]
        result = self.sizer.reconcile_with_broker(positions)

        # All 3 prior entries nuked, only the broker-derived entry remains.
        assert len(self.sizer.open_positions) == 1
        assert "seeded_broker-pos-1" in self.sizer.open_positions
        assert result["before_count"] == 3
        assert result["after_count"] == 1
        assert result["seeded_count"] == 1

    def test_reconcile_logs_before_after_counts(self, caplog):
        """The reconciliation log entry must show before→after counts so
        operators can verify divergence."""
        import logging

        self.sizer.register("phantom-1", 50.0)
        self.sizer.register("phantom-2", 75.0)

        with caplog.at_level(logging.INFO, logger="risk.sl_position_sizer"):
            self.sizer.reconcile_with_broker([])

        log_lines = [rec.getMessage() for rec in caplog.records if "reconcile_with_broker" in rec.getMessage()]
        assert log_lines, "Expected a reconcile log entry"
        msg = log_lines[-1]
        assert "2→0" in msg
        assert "diverged=True" in msg

    def test_reconcile_returns_iso_timestamp(self):
        """Result includes a UTC ISO8601 ``ran_at`` field for audit logs."""
        result = self.sizer.reconcile_with_broker([])
        assert "ran_at" in result
        # Quick sanity check: looks like an ISO8601 timestamp.
        assert "T" in result["ran_at"]
        assert result["ran_at"].endswith("+00:00") or result["ran_at"].endswith("Z")

    def test_thread_safe_under_register_concurrent(self):
        """reconcile_with_broker holds _lock — concurrent register calls
        either complete before or after the swap, not interleaved."""
        import threading

        positions = [
            _FakeBrokerPos(
                position_id="seeded-1",
                symbol="EURUSD",
                volume=0.10,
                entry_price=1.0850,
                stop_loss=1.0820,
            ),
        ]
        errors: list[Exception] = []

        def do_reconcile():
            try:
                self.sizer.reconcile_with_broker(positions)
            except Exception as exc:
                errors.append(exc)

        def do_register(i: int):
            try:
                self.sizer.register(f"sig-{i}", 5.0)
            except Exception as exc:
                errors.append(exc)

        threads: list[threading.Thread] = []
        threads.append(threading.Thread(target=do_reconcile))
        for i in range(20):
            threads.append(threading.Thread(target=do_register, args=(i,)))

        for t in threads:
            t.start()
        for t in threads:
            t.join()

        assert errors == []
        # After the dust settles, reconcile ran LAST (or interleaved safely),
        # so _open_positions contains exactly the seeded entry — OR
        # it contains the seeded entry PLUS some live signals if
        # reconcile ran mid-way. The invariant we enforce is:
        # "seeded-1" is ALWAYS present after reconcile completes.
        assert "seeded_seeded-1" in self.sizer.open_positions


class TestComputePositionRiskUsd:
    """Direct tests for the module-level helper."""

    def test_eurusd_known_symbol(self):
        risk = _compute_position_risk_usd(
            symbol="EURUSD",
            entry_price=1.0850,
            sl_price=1.0820,  # 30 pips
            lots=0.50,
        )
        # 30 pips * 0.50 lots * $10/pip = $150
        assert risk == pytest.approx(150.0)

    def test_usdjpy_uses_correct_pip_size(self):
        risk = _compute_position_risk_usd(
            symbol="USDJPY",
            entry_price=154.000,
            sl_price=153.700,  # 30 pips on a pip_size=0.01 symbol
            lots=1.0,
        )
        # 30 pips * 1.0 lots * $6.5/pip = $195
        assert risk == pytest.approx(195.0)

    def test_no_sl_uses_conservative_fallback(self):
        risk = _compute_position_risk_usd(
            symbol="EURUSD",
            entry_price=1.0850,
            sl_price=None,
            lots=0.20,
        )
        # 0.20 lots * $100/lot fallback
        assert risk == pytest.approx(20.0)

    def test_unknown_symbol_falls_back_to_fx_defaults(self):
        risk = _compute_position_risk_usd(
            symbol="ZARUSD",
            entry_price=0.0550,
            sl_price=0.0520,  # 30 pips at pip_size=0.0001
            lots=0.10,
        )
        # 30 pips * 0.10 lots * $10/pip = $30
        assert risk == pytest.approx(30.0)

    def test_zero_lots_returns_zero(self):
        risk = _compute_position_risk_usd(
            symbol="EURUSD",
            entry_price=1.0850,
            sl_price=1.0820,
            lots=0.0,
        )
        # Zero lots → conservative fallback (0 * $100 = 0)
        assert risk == 0.0


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
